name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main@sha256:6f9370f3437840c438616e2abb16131a485cac57eb928b941e22783c57baf985
    steps:
    - uses: actions/checkout@v4

    - name: Fetch full clone
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile project
      id: make
      run: |
        make

    - name: Upload ELF
      uses: actions/upload-artifact@v4
      if: steps.make.outcome == 'success'
      with:
        name: nhddl
        path: |
          nhddl-*.elf
          !nhddl-*_unc.elf

    - name: Upload YAML examples
      if: steps.make.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: examples
        path: |
          examples/*.yaml

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Fetch full clone
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Get git describe
      run: |
        echo "GIT_VERSION=$(git describe --always --dirty --tags --exclude nightly)" >> $GITHUB_ENV

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Prepare release archive
      run: |
        mv nhddl/nhddl-${{ env.GIT_VERSION }}.elf nhddl.elf
        zip -r nhddl-${{ env.GIT_VERSION }}.zip nhddl.elf examples

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          nhddl-${{ env.GIT_VERSION }}.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        files: |
          nhddl-${{ env.GIT_VERSION }}.zip
