name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - uses: actions/checkout@v4

    - name: Fetch full clone
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile project
      id: make
      run: |
        make

    - name: Upload ELF
      uses: actions/upload-artifact@v4
      if: steps.make.outcome == 'success'
      with:
        name: test
        path: |
          test.elf
          !test_unc.elf

